Support for processing forward messages
hyperledger/aries-vcx pull request #1028
Opened 2023-10-26 10:02 UTC by nain-F49FF806

2023-10-26 13:08 UTC, Patrik-Stas commented on agents/rust/mediator/mediation/src/didcomm_types.rs
> +    // pub fn default_alice() -> ForwardMsg {
delete if not needed

2023-10-26 13:13 UTC, nain-F49FF806 commented on agents/rust/mediator/mediation/src/didcomm_types.rs
> +    // pub fn default_alice() -> ForwardMsg {
Done

2023-10-26 15:07 UTC, Patrik-Stas requested changes
left more comments which came to my mind as part of reviewing via DM, most of which are out of scope for this particular PR

2023-10-27 11:11 UTC, nain-F49FF806 commented on agents/rust/mediator/tests/mediator-routing-forward.rs
> +impl OneTimeInit for TestSetupAries {
Done. 

It was meant to be test-file specific setup code. But currently same setup is being run. 
So I have moved relevant setup into a common function.

2023-10-27 11:11 UTC, nain-F49FF806 commented on agents/rust/mediator/tests/mediator-routing-forward.rs
> +    agent_verikey: &VeriKey,
Noted.

Done.

2023-10-27 15:54 UTC, merged