Uniffi demo holder
hyperledger/aries-vcx pull request #1058
Opened 2023-11-11 19:23 UTC by swaptr

2023-11-11 19:26 UTC, swaptr commented on uniffi_aries_vcx/demo/app/src/main/java/org/hyperledger/ariesvcx/AppDemoController.kt
> +    }
@gmulhearn the credential is not accepted here (atm I am sort of forcing the credential to be accepted).

2023-11-21 20:42 UTC, Patrik-Stas commented on uniffi_aries_vcx/demo/app/src/main/res/raw/transactions
perhaps you could name this file something else - whatever network this is representing, currently it's not quite clear

But I think it would be also valuable to keep the "localhost" genesis in place as well. For anyone coming and wanting to build and develop locally, having localhost as default would be the minimal friction dev configuration

2023-11-23 11:01 UTC, gmulhearn commented on uniffi_aries_vcx/demo/app/src/main/res/raw/transactions
agreed on having a name which is specific to the network. 

Altho worth noting that localhost won't work given the most common usecase of this being built onto a separate android device. Maybe unless people are working with an emulator, not sure how networking works on emulators...

2023-11-23 11:07 UTC, gmulhearn commented on uniffi_aries_vcx/demo/app/src/main/java/org/hyperledger/ariesvcx/HolderScreen.kt
> +            title = { Text("Accept this invitation?") },
nit: should say "Accept this credential?"

2023-11-23 11:10 UTC, gmulhearn requested changes
Left some comments above, most just clean up stuff.

Also a general note: try to ensure that Kotlin calls into rust/uniffi are done within `Dispatchers.IO`. i.e. `..launch(Dispatchers.IO) {.. }`

For instance, `processOfferRequest` is launching with `viewModelScope.launch`, but you'd want to launch with `.launch(Dispatchers.IO)`. If you don't do this, then the Uniffi/rust calls are going to block the main UI thread, which is what causes UI freezes etc

2023-11-23 18:20 UTC, swaptr commented on uniffi_aries_vcx/demo/app/src/main/java/org/hyperledger/ariesvcx/HolderScreen.kt
> +    }
Yes I can confirm that the polling stops (more like pauses) when switching between screens.

2023-11-25 11:42 UTC, gmulhearn approved these changes

2023-11-25 11:42 UTC, merged