refactor: ledger & anoncreds typing, part 1
hyperledger/aries-vcx pull request #1116
Opened 2024-01-31 08:02 UTC by mirgee

Introduces a new crate, `anoncreds_types` (derived from `anoncreds-rs`) with ledger and anoncreds types.

Starts typing `base_anoncreds` and `base_ledger` traits, where each implementation has the responsibility of converting between the trait interface types and corresponding types of the library used for the implementation (`indy-vdr`, `anoncreds-rs`).

Explicating the information required by each implementation and formalizing the type conversions helps assuring correctness at compile time. Besides type safety when compared to passing strings, using custom types in the traits (as opposed to using types provided by a 3rd party library) also clearly separates dependencies of the implementation from the dependencies of the public interface.

Some of the code adopted from `anoncreds-rs` still requires a (dedicated) cleanup.

2024-02-01 15:43 UTC, Patrik-Stas commented on aries/aries_vcx/src/common/keys.rs
> +    did: &Did,
💌

2024-02-02 15:13 UTC, Patrik-Stas requested changes

2024-02-02 15:44 UTC, mirgee commented on aries/misc/anoncreds_types/src/data_types/macros.rs
Hell no, this is not staying 🙅‍♂️

2024-02-02 15:50 UTC, mirgee commented on aries/misc/anoncreds_types/src/data_types/mod.rs
> +pub mod messages;
Not unnecessary, it is intended for non-ledger types in `BaseAnoncreds`. Maybe messages is a wrong name.

2024-02-02 15:51 UTC, mirgee commented on aries/aries_vcx/src/common/primitives/credential_definition.rs
> +    schema_json: Schema,
Yes I know and agree

2024-02-02 15:52 UTC, mirgee commented on aries/misc/anoncreds_types/src/error.rs
> +    RevocationRegistryFull,
The entire error side of this crate needs to be reworked a simplified

2024-02-06 10:50 UTC, Patrik-Stas approved these changes

2024-02-06 10:51 UTC, merged