[WIP]: feat(mediator): Containerise and package mediator
hyperledger/aries-vcx pull request #1139
Opened 2024-02-29 07:59 UTC by nain-F49FF806

2024-03-01 04:30 UTC, Patrik-Stas requested changes
Just a small note about dev onboarding/documentation

2024-03-01 04:30 UTC, Patrik-Stas commented on aries/agents/rust/mediator/.env
Given the default dev configuration assumes that the database has certain configuration - eg. certain version of mysql, certain username and password, It would be nice to add small shell script to startup dependencies for local development - I guess for now that would by just the mysql. 
Then also add note in the `readme.md`

2024-03-04 10:24 UTC, Patrik-Stas submitted a review, later dismissed

2024-03-04 10:36 UTC, nain-F49FF806 commented
@Patrik-Stas I have added further small improvements to the readme. The push seems to have automatically made the review stale. But the changes are small, you can take a glance.

2024-03-05 06:27 UTC, merged