Replace openssl by crates 'num-bigint', 'sha2'
hyperledger/aries-vcx pull request #317
Opened 2021-07-12 12:21 UTC by Patrik-Stas

Signed-off-by: Patrik Stas <patrik.stas@absa.africa>

2021-07-12 15:04 UTC, mirgee requested changes
LGTM! 👍  However, there are many newly redundant references to openssl in Android and iOS build scripts, dockerfiles, `build.rs`, etc. I would prefer to remove these as part of this PR to avoid leaving the dead code rot indefinitely.

2021-07-14 11:30 UTC, Patrik-Stas commented
> LGTM! 👍 However, there are many newly redundant references to openssl in Android and iOS build scripts, dockerfiles, `build.rs`, etc. now. I would prefer to remove these as part of this PR to avoid letting the dead code rot indefinitely.

agree, will do

2023-01-09 12:26 UTC, gmulhearn commented
@Patrik-Stas just looking at old PRs. is this PR still relevant? libvcx doesn't depend on openssl anymore. but aries-vcx does, should it be migrated?

2023-08-04 20:56 UTC, gmulhearn submitted a review, later dismissed

2023-08-25 15:29 UTC, mirgee approved these changes

2023-08-26 18:57 UTC, mirgee approved these changes

2023-08-26 18:57 UTC, merged