Refactoring/ddo
hyperledger/aries-vcx pull request #528
Opened 2022-07-28 16:09 UTC by Patrik-Stas

2022-08-02 13:40 UTC, mirgee requested changes

2022-08-03 07:24 UTC, Patrik-Stas commented on aries_vcx/src/did_doc/model.rs
> +    #[serde(rename = "publicKeyBase58")] // todo: rename to publicKeyMultibase
created https://github.com/hyperledger/aries-vcx/issues/531

2022-08-03 07:27 UTC, Patrik-Stas commented on aries_vcx/src/did_doc/model.rs
> +#[derive(Debug, Deserialize, Serialize, Clone, PartialEq)]
We do need these here as this is part of DDO, and these are properties which we want to have on DDO. I agree probably some derived impls across the codebase could be removed

2022-08-03 07:29 UTC, Patrik-Stas commented on aries_vcx/src/did_doc/model.rs
> +mod unit_test {
Agreed, let's consolidate this in separate PR

2022-08-03 07:35 UTC, Patrik-Stas commented on aries_vcx/src/handlers/service_resolvable.rs
> +use crate::did_doc::service_aries::AriesService;
I wouldn't like to see it in `did_doc` - tried to keep that module clean of aries-vcx specifics as if we were to create independent crate out of it. 
I am think we can put it into `utils` though

2022-08-04 07:39 UTC, mirgee approved these changes

2022-08-04 07:39 UTC, merged