Inline value of recipient keys in ddo
hyperledger/aries-vcx pull request #535
Opened 2022-08-03 17:29 UTC by Patrik-Stas

Signed-off-by: Patrik Stas <patrik.stas@absa.africa>

2022-08-08 14:56 UTC, mirgee requested changes

2022-08-08 14:56 UTC, mirgee commented on aries_vcx/src/messages/connection/request.rs
> -                did_doc: _did_doc_vcx_new(),
Is this function still used somewhere?

2022-08-08 14:56 UTC, mirgee commented on aries_vcx/src/did_doc/mod.rs
> +    pub fn _did_doc_vcx_new_inlined_recipient_keys() -> DidDoc {
Isn't `_vcx_new_` pleonasmic? How about `_did_doc_inlined_recipient_keys`?

2022-08-18 07:01 UTC, Patrik-Stas commented on aries_vcx/src/messages/connection/request.rs
> -                did_doc: _did_doc_vcx_new(),
still has several usages

2022-08-18 07:04 UTC, Patrik-Stas commented on aries_vcx/src/messages/connection/request.rs
> -                did_doc: _did_doc_vcx_new(),
removed

2022-08-18 07:04 UTC, Patrik-Stas commented on aries_vcx/src/did_doc/mod.rs
> +    pub fn _did_doc_vcx_new_inlined_recipient_keys() -> DidDoc {
renamed

2022-08-18 13:46 UTC, merged