revealed parameter in prover building proof
hyperledger/aries-vcx pull request #668
Opened 2022-11-28 07:45 UTC by pomfar

Signed-off-by: Pompeo Faruolo <pompeo.faruolo@etuitus.it>

2022-11-28 19:08 UTC, Patrik-Stas commented
hi @pomfar can you please leave write up some description about these changes? Is this in order to be more explicit, or does this have any functional effect?

Thank you.

2022-11-29 05:29 UTC, pomfar commented
Hi 
the change is a fix in the generating of the proof response, where the parameter unrevealed was ignored and set to true.
Then the proof response always revealed all attribute values, even when revealed parameter in input was false.

2022-12-01 17:59 UTC, Patrik-Stas commented
Hi @pomfar, this looks reasonable. 👍 

I've never used `revealed: false`; if prover specifies this, what happens? I suppose this way the prover only proves ownership of the attribute, but the value?

Before we merge this, I would like to ask you for a favor - can you please rebase this on top of https://github.com/hyperledger/aries-vcx/pull/648 ? This is currently sort of top priority PR and @gmulhearn-anonyome has been already rebasing many times, I hope you understand. In that PR, the files you have modified has been shuffled a bit. Please reach out to @gmulhearn-anonyome on discord if it turns our tricky and a guidance is needed. 

Thank you!

2022-12-02 09:54 UTC, pomfar commented
Hi
Yes, with revealed=false the values is not sent to the verifier.
This is a very powerful feature!

For the rebase, it's ok.

thanks

2022-12-05 13:55 UTC, Patrik-Stas commented on aries_vcx/src/common/proofs/prover/prover_internal.rs
> +                let mut revealed = true;
This block of added code can be done more safer, simpler:
```
let revealed = value["credential"]["cred_info"]["revealed"].as_bool().unwrap_or_default(true);
```
Although your code seems fine, this 1 liner is less error prone for 3 reasons:
- no `mut`
- no risk of mismatching strings in conditions and assignment, no duplication
- no panicking `unwrap()`

2022-12-05 13:56 UTC, Patrik-Stas commented on aries_vcx/src/common/proofs/prover/prover_internal.rs
>  pub async fn build_schemas_json_prover(
bonus points to add test checking that `build_schemas_json_prover` produces `revealed: true` by default and `revealed: false` if overriden

2022-12-05 13:58 UTC, Patrik-Stas requested changes
Hi @pomfar sorry for taking long time to merge this, we can speed things up now that the big PR from George has been merged into 0.50.0.
Just small change requested in the comment and this can be merged.

2022-12-08 09:33 UTC, Patrik-Stas commented on aries_vcx/src/common/proofs/prover/prover_internal.rs
> +                    revealed: revealed,
syntax allows you to write simply 
```
revealed
```
here instead of 
```
revealed: revealed
```

2022-12-08 09:33 UTC, Patrik-Stas approved these changes
I think you misunderstood my previous comment a little, the `CredInfoProver`'s `revealed` did not have to `Option`, instead it'd be better if line 118 `credential_def_identifiers` defaulted to true
```
let revealed = value["credential"]["cred_info"]["revealed"].as_bool().unwrap_or(true);
```
Now injecting default value is deferred to latter step `build_requested_credentials_json`. It's no biggie, I'll merge it as it is. If you'd like, you can refactor in separate PR.

2022-12-08 09:34 UTC, merged