Simplify connection serialization from nodejs
hyperledger/aries-vcx pull request #749
Opened 2023-02-10 11:37 UTC by Patrik-Stas

Signed-off-by: Patrik Stas <patrik.stas@absa.africa>

2023-02-10 16:00 UTC, bobozaur requested changes
Not related to the code itself, but rather to the base branch.
I think it would be best to merge #739 and merge this into main afterwards.

The current state of #739 behaves exactly the way main currently does. This PR changes that, which is why I think it deserves it's separate spot for code history's reasons.

2023-02-14 09:08 UTC, bobozaur approved these changes
Looks good!

2023-02-14 11:31 UTC, mirgee approved these changes

2023-02-14 11:31 UTC, mirgee commented on wrappers/node/src/api/common.ts
>  export interface ISerializedData<T> {
Note: we agreed to remove the assumptions this interface makes about the serialization format (i.e. containing `source_id`, `data`, `version` or any other fields, but the assumption of it being a JSON will stay for now).

2023-02-14 11:32 UTC, merged