post_message migration [Issue #772]
hyperledger/aries-vcx pull request #790
Opened 2023-04-03 19:37 UTC by Andy-Waine

Resolves: Issue https://github.com/hyperledger/aries-vcx/issues/772 - Move out post_message to shared_vcx

###Short summary
-Migrated httpclient.rs file to shared_vcx directory
-The issue requested that the post_message() function be moved, but there were other items within httpclient.rs that post_message() depended upon.
-aries-vcx is successfully compiling with the changes provided.

2023-04-04 08:34 UTC, Patrik-Stas commented on agency_client/src/internal/messaging.rs139
seems like this file was created by accident?

2023-04-04 08:43 UTC, Patrik-Stas requested changes
Left few comments, also note that some testing jobs are failing. Take a look at which jobs are failing, what test command they run in order to reproduce the issues locally.

2023-04-04 08:43 UTC, Patrik-Stas commented on shared_vcx/src/errors/error.rs
> +pub enum SharedAgencyClientErrorKind {
There already is `SharedVcxErrorKind` under `shared_vcx/src/errors/error.rs`, just extend that one please

2023-04-04 08:43 UTC, Patrik-Stas commented on shared_vcx/src/errors/error.rs
> +pub enum SharedAgencyClientErrorKind {
Please also check if all of these added error kinds are actually being used.

2023-04-04 08:43 UTC, Patrik-Stas commented on shared_vcx/src/testing/mocking.rs
It seems this is copied from `agency_client` - can the original `mocking.rs` be deleted now?

2023-04-04 09:10 UTC, Patrik-Stas commented
One more recommendation - when you are working on a pull request, it's better when you create and working within a custom feature branch. 
It's then easier 
- for maintainers of target repository checkout your work locally and take a better look at changes
- also for you, because since in your forked repository you pushed commits to `main`, it will have conflicts with `hyperledger/aries-vcx` and you won't be able to sync it.

2023-04-05 15:35 UTC, Andy-Waine commented
Hey @Patrik-Stas thank you for the recommendations, I will work on those next. In regards to cutting a feature branch, I attempted that initially, but when I tried to push the branch to the `aries-vcx` repo, I received an error stating that I did not have the proper permissions to push, leading me to fork. I'll look into it some more and try again.

Thanks!

2023-04-05 16:26 UTC, Patrik-Stas commented
> Hey @Patrik-Stas thank you for the recommendations, I will work on those next. In regards to cutting a feature branch, I attempted that initially, but when I tried to push the branch to the `aries-vcx` repo, I received an error stating that I did not have the proper permissions to push, leading me to fork. I'll look into it some more and try again.
> 
> Thanks!

Yes, pushing branch directly under Hyperledger repo won't work. The recommendation is that even though it's your own fork, it's better to work on a feature branch within your fork. And then it's easy to keep your `main` branch in sync with the origin (hyperledger) `main` branch

2023-04-12 19:30 UTC, Andy-Waine commented
> Yes, pushing branch directly under Hyperledger repo won't work. The recommendation is that even though it's your own fork, it's better to work on a feature branch within your fork. And then it's easy to keep your `main` branch in sync with the origin (hyperledger) `main` branch

I understand now. Thank you for the clarification, @Patrik-Stas!

2023-04-12 19:51 UTC, closed without merging