Uniffi android controller
hyperledger/aries-vcx pull request #984
Opened 2023-09-18 09:18 UTC by swaptr

Credits to @gmulhearn for simplifying the android code by adding a controller. :rocket: 
Merge after #970

2023-09-24 20:43 UTC, gmulhearn commented
Nice, let me know once this has been rebased and ready to review 👌. Also, please make sure that the CI lint checks are satisfied

2023-09-25 00:36 UTC, gmulhearn approved these changes

2023-09-25 00:39 UTC, gmulhearn requested changes
Not sure that removing the "mut"s was the right decision. You might need to revert that and then workspace_clippy and test-Int-Aries-vcx-migration CI jobs should pass

2023-09-25 01:08 UTC, gmulhearn-anonyome approved these changes

2023-09-25 01:09 UTC, gmulhearn approved these changes

2023-09-25 03:28 UTC, merged